package com.luma.entity.enums;

public enum NotificationType {
    SYSTEM,
    EVENT_CREATED,
    EVENT_APPROVED,
    EVENT_REJECTED,
    EVENT_REMINDER,
    EVENT_UPDATE,
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    NEW_FOLLOWER,
    QUESTION_ANSWERED,
    NEW_REGISTRATION,
    NEW_QUESTION,
    REGISTRATION_CANCELLED,
    REPLY_MESSAGE,
    BROADCAST,
    PAYMENT,
    WITHDRAWAL_REQUEST,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,
    WITHDRAWAL_COMPLETED
}
