package com.luma.entity.enums;

public enum ActivityType {
    LOGIN,
    LOGOUT,
    REGISTER,
    UPDATE_PROFILE,
    CHANGE_PASSWORD,
    CREATE_EVENT,
    UPDATE_EVENT,
    CANCEL_EVENT,
    REGISTER_EVENT,
    CANCEL_REGISTRATION,
    APPROVE_REGISTRATION,
    REJECT_REGISTRATION,
    FOLLOW_ORGANISER,
    UNFOLLOW_ORGANISER,
    ASK_QUESTION,
    ANSWER_QUESTION,
    CREATE_ORGANISER_PROFILE
}
